name:                school-of-expression
version:             0.1.0.0
github:              "caasi/school-of-expression"
license:             BSD3
author:              "caasi Huang"
maintainer:          "caasi.igd@gmail.com"
copyright:           "Copyright: (c) 2016 caasi Huang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/caasi/school-of-expression#readme>

dependencies:
- base >= 4.7 && < 5
- HGL <= 3.2.3.1
- ghc-prim <= 0.5.1.1

library:
  source-dirs: src

executables:
  school-of-expression-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - school-of-expression

tests:
  school-of-expression-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - school-of-expression
